CartPole-v1:
  gamma: 0.99
  batch_size: 128
  hidden_size: 128
  hidden_size2: 128

  replay_size: 1.0e+6
  replay_size_start: 5000

  epsilon_decay: 10000
  epsilon_final: 0.0000
  epsilon_start: 0.250

  
  

  

  stopping_reward: 475
  max_frames: 5.0e+5

  save_path: saved_models/q4_hard
  target_net_sync: 1000

  tau: 0.005
  alpha_sync: false

  clip_gradient: false