LunarLander-v3:

  hidden_size: 256
  hidden_size2: 256

  
  learning_rate: 0.0001
  gamma: 0.99
  replay_size: 200000
  replay_size_start: 50000
  batch_size: 128
  clip_gradient: true


  alpha_sync: true
  tau: 0.005
  target_net_sync: 2000     


  epsilon_start: 1.0
  epsilon_final: 0.01
  epsilon_decay: 300000      


  max_frames: 2000000
  stopping_reward: 200      
  save_path: "saved_models/lander_lr1e4"